# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f3bf16817207ae22c7e1686ccfbb181e4e74ff85808270e53f243b802e57d05192d30fafd1074e4381f099d14aa52dec1944b8b0b2f5a4b193ba231e30ac2ce

test:
  secret_key_base: edd7ea1a99c66ced7f94555f6a56e98253797006572997fb027f8f64ed1b07e9304177fa818dfbbab85fabc04b84c32c9236fa1a9a751d753d44189dfd0a968d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
